---
name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@a42157e21f91d87ff97e4a6a30f431f687052064
    with:
      apt_packages: >-
        pkg-config
        libegl1-mesa-dev
        libpipewire-0.3-dev
        libgbm-dev
