name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    uses: riccione/github-workflows/.github/workflows/rust-ci.yml@v3
    with:
      apt_packages: >-
        pkg-config
        libegl1-mesa-dev
        libpipewire-0.3-dev
        libgbm-dev
