name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  release:
    uses: riccione/github-workflows/.github/workflows/release.yml@v3
    permissions:
      contents: write
    with:
      bin_name: rgrim
      tag: ${{ github.ref_name }}
      apt_packages: >-
        pkg-config
        libegl1-mesa-dev
        libpipewire-0.3-dev
        libgbm-dev
